version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: rune
    main: ./cmd/rune
    binary: rune
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

brews:
  - name: rune
    repository:
      owner: sidkhuntia
      name: rune
    directory: Formula
    homepage: https://github.com/sidkhuntia/rune
    description: "AI-powered Git commit message generator"
    license: MIT
    test: |
      system "#{bin}/rune --help"
    install: |
      bin.install "rune"
    custom_require: ""
    custom_block: |
      head "https://github.com/sidkhuntia/rune.git"
